schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "ContextPie"
version = "0.9.6"
name = "Context Pie"
tagline = "Context sensitive pie menu for a simple, fast workflow"
maintainer = "Bastian L Strube <mail@bastianlstrube.dk>"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional: add-ons can list which resources they will require:
# permissions = []

# Optional link to documentation, support, source files, etc
website = "https://github.com/bastianlstrube/ContextPie"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/extensions/tags.html
tags = ["User Interface", "3D View", "UV"]

blender_version_min = "4.2.0"
# Optional: maximum supported Blender version
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]


longdescription = """
## Context sensitive pie menu
Brings pie menus to poly modeling, curve editing, uv mapping and animation.
Replaces the traditional context sensitive menu with a pie menu, enabling many more functions on the same hotkey. Pie menus also lets muscle memory navigate the menus much faster than reading through a long list will. 
Meant to work in conjunction with Blender's official pie-menu add-on.

## Shortcuts
**Right Mouse** :                    Mode selection pie menu

**Shift + Right Mouse**:        Context sensitive pie menu

**Ctrl + Right Mouse**:         Pivots & snap pie menu

Made following an ancient Mayan pie recipe and works well with the industry compatible keymap.

RELEASE NOTES:
First test version using the extensions website.

Context menu functions in these contexts:
 * Object Mode
 * Edit Mesh
 * Edit Curve 
 * UV Editor
 * Pose Mode
 * Edit Armature
"""